### ISSUE TITLE
Load failed

### ISSUE THREAD

**Issue by hugoKs3** [angryziber/synology-cast-photos#2]
Hello and thanks a lot for this great piece of code!
I try to use with my "old" Synology (DS212j) and only through the browser for now (I'll try with the Chromecast later).
I thus call the /receiver app from my browser, hit Esc to specify the folder but it "partially works".

The script lists the photos, get the metadata of each one, but can't display the photo itself. On the bottom-right, I have the "xxx/yyy: failed" message for each photo. 

I followed your installation instructions, set the mode to "img", added my photo directory to php base-dir.

Any idea of what I'm doing wrong?

Thanks a lot

**Comment by angryziber** [comment]
Sorry for the late answer. There may be several reasons:
1. You have wrong $photos_dir in config.php, make sure it's correct
2. PHP is not allowed to read $photos_dir (this should be configured in Synology DSM)
3. Make sure you have `mode: 'img' ` in receiver/config.js because your hardware is too slow to convert photos to 4k videos

Anyway, check in Network tab that photos are loaded using `photo.php`, not `photov.php` and see what is the status code (e.g. Forbidden would indicate a file permissions issue)
